version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/amwolff/awsig.hashBuilder).Write
        - (*github.com/amwolff/awsig.hashBuilder).WriteByte
        - (*github.com/amwolff/awsig.hashBuilder).WriteString
    gosec:
      excludes:
        - G101
        - G104 # handled by errcheck
        - G401
        - G501
        - G505
    govet:
      disable:
        - fieldalignment
        - shadow # a ton of false positives
      enable-all: true
    misspell:
      locale: US
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/amwolff/awsig
run:
  timeout: 5m
  modules-download-mode: readonly
